### ISSUE TITLE
PirateStealer .exe files don't work

### ISSUE THREAD

**Issue by LKOKLK** [PirateMonster/PirateStealer#10]
When i open the ,exe that https://ps.piratemonster.dev/builder produces it logs me out of discord, but doesn't send the information to a webhook as it should. I have tried making a new webhook etc but it just doesn't work.

**Comment by PHOeNIX276** [comment]
In my case the Website won't even build the exe file

**Comment by bytixo** [comment]
it only send the info if you log back in
