### ISSUE TITLE
Unable to understand how to use it

### ISSUE THREAD

**Issue by PHOeNIX276** [PirateMonster/PirateStealer#8]
Hi,
I installed the ZIP FILE FROM GITHUB and was wondering on how to use it,
it would be great if you could guide me through on how can I start with this.
I know the part where I have to send the grabber which will be made through this to the people
I just need help on how do I make the Grabber file which I gotta send to people
Thanks,

**Comment by Stanley-GF** [comment]
https://ps.piratemonster.dev

**Comment by PHOeNIX276** [comment]
Even after i executed the exe i didn't get any info

**Comment by Stanley-GF** [comment]
Try to build again ^^ I fixed !
